-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 19:45:55 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema taxdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taxdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taxdb` DEFAULT CHARACTER SET utf8 ;
USE `taxdb` ;

-- -----------------------------------------------------
-- Table `taxdb`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxdb`.`company` ;

CREATE TABLE IF NOT EXISTS `taxdb`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
